export const headers = [
  "Name",
  "Email",
  "Phone No",
  "Order Date & Time",
  "User ID",
  "Order ID",
  "Assigned Lawyer",
  "Status",
  "City",
  "State",
  "Concerned Area",
  "Device",
  "Categories",
  "Sub-Categories",
  "Order Status",
  "Sale Value",
  "Coupon Code",
  "Coupon Discount",
  "CGST",
  "SGST",
  "IGST",
  "Order Value",
  "TDS",
  "Invoice",
  "Invoice No.",
  "Transaction No.",
  "Razorpay Order ID",
  "Razorpay Payment ID",
];
const orderData = [
  {
    name: "Charlie Donin",
    email: "wdavis@aol.com",
    phone: "+91 981 897 8812",
    orderDate: "20 Aug 2024, 17:00",
    userId: "#12OC24A1",
    orderId: "#12OC24A1",
    assignedLawyer: "Charlie Donin",
    status: "Not Started",
    city: "Lucknow",
    state: "Uttar Pradesh",
    concernedArea: "blog/how-to-register-a-private-limited-company",
    device: "mobile",
    category: "incorporation",
    subCategory: "private limited registration",
    orderStatus: "Payment Failed",
    saleValue: "₹8500",
    couponCode: "NOVAM20",
    couponDiscount: "₹1700",
    cgst: "₹850",
    sgst: "₹850",
    igst: "₹0",
    orderValue: "₹6800",
    tds: false,
    invoiceNo: "123",
    transactionNo: "T12345",
    razorpayOrderId: "#ORD1234",
    razorpayPaymentId: "#PAY1234",
  },
  {
    name: "Makenna Carder",
    email: "ltorres@aol.com",
    phone: "+91 998 872 8812",
    orderDate: "18 Aug 2024, 14:30",
    userId: "#12OC24A2",
    orderId: "#12OC24A2",
    assignedLawyer: "Makenna Carder",
    status: "Completed",
    city: "Delhi",
    state: "Delhi",
    concernedArea: "blog/how-to-start-a-partnership",
    device: "pc",
    category: "business registration",
    subCategory: "partnership registration",
    orderStatus: "Paid",
    saleValue: "₹9500",
    couponCode: "PART50",
    couponDiscount: "₹500",
    cgst: "₹425",
    sgst: "₹425",
    igst: "₹0",
    orderValue: "₹8500",
    tds: true,
    invoiceNo: "124",
    transactionNo: "T12346",
    razorpayOrderId: "#ORD1235",
    razorpayPaymentId: "#PAY1235",
  },
  {
    name: "Talan Dokidis",
    email: "rtaylor@aol.com",
    phone: "+91 889 897 8813",
    orderDate: "15 Aug 2024, 11:00",
    userId: "#12OC24A3",
    orderId: "#12OC24A3",
    assignedLawyer: "Talan Dokidis",
    status: "Completed",
    city: "Mumbai",
    state: "Maharashtra",
    concernedArea: "blog/how-to-register-a-limited-liability-partnership",
    device: "mobile",
    category: "llp registration",
    subCategory: "limited liability partnership",
    orderStatus: "Paid",
    saleValue: "₹10000",
    couponCode: "LLP10",
    couponDiscount: "₹1000",
    cgst: "₹450",
    sgst: "₹450",
    igst: "₹0",
    orderValue: "₹8550",
    tds: false,
    invoiceNo: "125",
    transactionNo: "T12347",
    razorpayOrderId: "#ORD1236",
    razorpayPaymentId: "#PAY1236",
  },
  {
    name: "Cheyenne Levin",
    email: "ebrown@aol.com",
    phone: "+91 777 897 8814",
    orderDate: "12 Aug 2024, 09:45",
    userId: "#12OC24A4",
    orderId: "#12OC24A4",
    assignedLawyer: "Cheyenne Levin",
    status: "Completed",
    city: "Bengaluru",
    state: "Karnataka",
    concernedArea: "blog/how-to-register-as-a-proprietorship",
    device: "pc",
    category: "business registration",
    subCategory: "proprietorship registration",
    orderStatus: "Paid",
    saleValue: "₹12000",
    couponCode: "PRO20",
    couponDiscount: "₹2400",
    cgst: "₹480",
    sgst: "₹480",
    igst: "₹0",
    orderValue: "₹9120",
    tds: true,
    invoiceNo: "126",
    transactionNo: "T12348",
    razorpayOrderId: "#ORD1237",
    razorpayPaymentId: "#PAY1237",
  },
  {
    name: "James Aminoff",
    email: "slee@aol.com",
    phone: "+91 766 897 8815",
    orderDate: "10 Aug 2024, 16:20",
    userId: "#12OC24A5",
    orderId: "#12OC24A5",
    assignedLawyer: "James Aminoff",
    status: "In Progress",
    city: "Chennai",
    state: "Tamil Nadu",
    concernedArea: "blog/how-to-register-a-private-limited-company",
    device: "mobile",
    category: "incorporation",
    subCategory: "private limited registration",
    orderStatus: "Refunded",
    saleValue: "₹8500",
    couponCode: "INC25",
    couponDiscount: "₹2125",
    cgst: "₹318.75",
    sgst: "₹318.75",
    igst: "₹0",
    orderValue: "₹5737.5",
    tds: false,

    invoiceNo: "",
    transactionNo: "",
    razorpayOrderId: "#ORD1238",
    razorpayPaymentId: "",
  },
];
export const consolidateHeader = [
  "Expert Name",
  "Expert Email",
  "Expert Phone No",
  "Prof Fees",
  "Amt Paid",
  "Amt Due",
  "Bank Name",
  "Acc Holder's Name",
  "Acc No",
  "IFSC Code",
  "PAN Number",
];
export const consolidateData = [
  {
    Expert_Name: "Charlie Donin",
    Expert_Email: "wdavis@aol.com",
    Expert_Phone_No: "+91 981 897 8812",
    Prof_Fees: "₹500",
    Amt_Paid: "₹6500",
    Amt_Due: "₹1700",
    Bank_Name: "SBI",
    Acc_Holder_Name: "Ram Kumar Sharma",
    Acc_No: "SBINO1889838N73",
    IFSC_Code: "SBINO1889838N73",
    PAN_Number: "SBIN01889838N73",
  },
  {
    Expert_Name: "Makenna Carder",
    Expert_Email: "Itorres@aol.com",
    Expert_Phone_No: "+91 981 897 8812",
    Prof_Fees: "₹500",
    Amt_Paid: "₹8500",
    Amt_Due: "₹1700",
    Bank_Name: "Punjab National Bank",
    Acc_Holder_Name: "Ram Kumar Sharma",
    Acc_No: "SBINO1889838N73",
    IFSC_Code: "SBINO1889838N73",
    PAN_Number: "SBIN01889838N73",
  },
  {
    Expert_Name: "Talan Dokidis",
    Expert_Email: "rtaylor@aol.com",
    Expert_Phone_No: "+91 981 897 8812",
    Prof_Fees: "₹8500",
    Amt_Paid: "₹8500",
    Amt_Due: "₹1700",
    Bank_Name: "Bank Of Baroda",
    Acc_Holder_Name: "Ram Kumar Sharma",
    Acc_No: "SBINO1889838N73",
    IFSC_Code: "SBINO1889838N73",
    PAN_Number: "SBINO1889838N73",
  },
  {
    Expert_Name: "Cheyenne Levin",
    Expert_Email: "ebrown@aol.com",
    Expert_Phone_No: "+91 981 897 8812",
    Prof_Fees: "₹8500",
    Amt_Paid: "₹8500",
    Amt_Due: "₹1700",
    Bank_Name: "Punjab National Bank",
    Acc_Holder_Name: "Ram Kumar Sharma",
    Acc_No: "SBINO1889838N73",
    IFSC_Code: "SBINO1889838N73",
    PAN_Number: "SBINO1889838N73",
  },
  {
    Expert_Name: "James Aminoff",
    Expert_Email: "slee@aol.com",
    Expert_Phone_No: "+91 981 897 8812",
    Prof_Fees: "₹8500",
    Amt_Paid: "₹8500",
    Amt_Due: "₹1700",
    Bank_Name: "Punjab National Bank",
    Acc_Holder_Name: "Ram Kumar Sharma",
    Acc_No: "SBINO1889838N73",
    IFSC_Code: "SBINO1889838N73",
    PAN_Number: "SBINO1889838N73",
  },
];
export const individualHeader = [
  "Order Date",
  "Completion Date",
  "Customer Name",
  "Customer Email",
  "Customer Phone No",
  "Order ID",
  "Sub Category",
  "Category",
  "Prof Fees",
  "Amt Paid",
  "Amt Due",
];
export const individualData = [
  {
    Order_Date: "05-10-2024|7:00pm",
    Completion_Date: "08-10-2024 7:00pm",
    Customer_Name: "Charlie Donin",
    Customer_Email: "wdavis@aol.com",
    Customer_Phone_No: "+91 981 897 8812",
    Order_ID: "D407F9K3N6T2PBW1X0H5M7Q2",
    Sub_Category: "Property Dispute Consultation",
    Category: "Business Legal",
    Prof_Fees: "₹8500",
    Amt_Paid: "₹8500",
    Amt_Due: "₹1700",
  },
  {
    Order_Date: "05-10-2024|7:00pm",
    Completion_Date: "08-10-2024 7:00pm",
    Customer_Name: "Makenna Carder",
    Customer_Email: "Borres Deol.com",
    Customer_Phone_No: "+01 061 807 8812",
    Order_ID: "D407F5K3NGT2PSW1X0HSM702",
    Sub_Category: "Property Dispute Consultation",
    Category: "Business Legal",
    Prof_Fees: "₹8500",
    Amt_Paid: "₹8500",
    Amt_Due: "₹1700",
  },
  {
    Order_Date: "05-10-2024|7:00pm",
    Completion_Date: "08-10-2024 7:00pm",
    Customer_Name: "Talari Dokidis",
    Customer_Email: "taylor@aol.com",
    Customer_Phone_No: "+91 081 897 812",
    Order_ID: "D407F8K3N6T2P8W1X0H5M7Q2",
    Sub_Category: "Property Dispute Consultation",
    Category: "Business Legal",
    Prof_Fees: "₹8500",
    Amt_Paid: "₹8500",
    Amt_Due: "₹1700",
  },
  {
    Order_Date: "05-10-2024|7:00pm",
    Completion_Date: "08-10-2024 7:00pm",
    Customer_Name: "Cheyenne Levin",
    Customer_Email: "ebrown@aol.com",
    Customer_Phone_No: "+91 981 897 8812",
    Order_ID: "D407F9K3N6T2PBW1X0H5M702",
    Sub_Category: "Property Dispute Consultation",
    Category: "Business Legal",
    Prof_Fees: "₹8500",
    Amt_Paid: "₹8500",
    Amt_Due: "₹1700",
  },
  {
    Order_Date: "05-10-2024|7:00pm",
    Completion_Date: "08-10-2024 7:00pm",
    Customer_Name: "James Aminoff",
    Customer_Email: "slee@aol.com",
    Customer_Phone_No: "+91 981 897 8812",
    Order_ID: "D407F9K3N6T2PBW1X0HSM7Q2",
    Sub_Category: "Property Dispute Consultation",
    Category: "Business Legal",
    Prof_Fees: "₹8500",
    Amt_Paid: "₹8500",
    Amt_Due: "₹1700",
  },
];
export const leadHeader = [
  "Name",
  "Email",
  "Phone No",
  "Lead Date & Time",
  "Concerned Area",
  "Device",
  "Service",
  "Product Name",
];
export const leadData = [
  {
    Name: "Charlie Donin",
    Email: "wdavis@aol.com",
    Phone_No: "+91 981 897 8812",
    Lead_Date: "20 Aug 2024, 17:00",
    Concerned_Area: "blog/how-to-register-a-private-limited-company",
    Device: "mobile",
    Service: "incorporation",
    Product_Name: "private limited registration",
  },
  {
    Name: "Makenna Carder",
    Email: "Itorres@aol.com",
    Phone_No: "+91 981 897 8812",
    Lead_Date: "20 Aug 2024, 17:00",
    Concerned_Area: "blog/how-to-register-a-private-limited-company",
    Device: "mobile",
    Service: "incorporation",
    Product_Name: "private limited registration",
  },
  {
    Name: "Talan Dokidis",
    Email: "rtaylor@aol.com",
    Phone_No: "+91 981 897 8812",
    Lead_Date: "20 Aug 2024, 17:00",
    Concerned_Area: "blog/how-to-register-a-private-limited-company",
    Device: "pc",
    Service: "incorporation",
    Product_Name: "private limited registration",
  },
  {
    Name: "Cheyenne Levin",
    Email: "ebrown@aol.com",
    Phone_No: "+91 981 897 8812",
    Lead_Date: "20 Aug 2024, 17:00",
    Concerned_Area: "blog/how-to-register-a-private-limited-company",
    Device: "pc",
    Service: "incorporation",
    Product_Name: "private limited registration",
  },
  {
    Name: "James Aminoff",
    Email: "slee@aol.com",
    Phone_No: "+91 981 897 8812",
    Lead_Date: "20 Aug 2024, 17:00",
    Concerned_Area: "blog/how-to-register-a-private-limited-company",
    Device: "mobile",
    Service: "incorporation",
    Product_Name: "private limited registration",
  },
];
export const lawyerMangagementHeader = [
  "Name",
  "Email",
  "Phone No",
  "Order Date & Time",
  "Expert's ID",
  "Online Status",
  "City",
  "State",
  "Specialization",
  "Bar Council ID",
  "Bar Council ID Proof",
  "Prof Type",
  "Degree",
  "Language",
  "Bank Name",
  "Acc Holder's Name",
  "Acc No",
  "IFSC Code",
  "PAN Number",
  "Cancel Cheque Image",
];
export const lawyerManagementData = [
  {
    Action: "Disapprove",
    Name: "Charlie Donin",
    Email: "wdavis@aol.com",
    Phone_No: "+91 897 897 8812",
    Order_Date: "20 Aug 2024, 17:00",
    Expert_ID: "#120C24A1",
    Online_Status: "Inactive",
    City: "Lucknow",
    State: "Uttar Pradesh",
    Specialization: "Agreement management",
    Bar_Council_ID: "#WW947U",
    Prof_Type: "Lawyer",
    Degree: "B. Com",
    Language: "English",
    Bank_Name: "SBI",
    Acc_Holder_Name: "Ram Kumar Sharma",
    Acc_No: "SBIN0188983BN73",
    IFSC_Code: "SBIN0188983BN73",
    PAN_Number: "SBIN0188983BN73",
  },
  {
    Action: "Approve",
    Name: "Makenna Carder",
    Email: "Itorres@aol.com",
    Phone_No: "+91 897 897 8812",
    Order_Date: "20 Aug 2024, 17:00",
    Expert_ID: "#120C24A1",
    Online_Status: "Active",
    City: "Lucknow",
    State: "Uttar Pradesh",
    Specialization: "Agreement management",
    Bar_Council_ID: "#WW947U",
    Prof_Type: "CA",
    Degree: "B. Com",
    Language: "English",
    Bank_Name: "Punjab National Bank",
    Acc_Holder_Name: "Ram Kumar Sharma",
    Acc_No: "SBIN0188983BN73",
    IFSC_Code: "SBIN0188983BN73",
    PAN_Number: "SBIN0188983BN73",
  },
  {
    Action: "Approve",
    Name: "Talan Dokidis",
    Email: "rtaylor@aol.com",
    Phone_No: "+91 897 897 8812",
    Order_Date: "20 Aug 2024, 17:00",
    Expert_ID: "#120C24A1",
    Online_Status: "Active",
    City: "Lucknow",
    State: "Uttar Pradesh",
    Specialization: "Agreement management",
    Bar_Council_ID: "#WW947U",
    Prof_Type: "Lawyer",
    Degree: "B. Com",
    Language: "English",
    Bank_Name: "Bank Of Baroda",
    Acc_Holder_Name: "Ram Kumar Sharma",
    Acc_No: "SBIN0188983BN73",
    IFSC_Code: "SBIN0188983BN73",
    PAN_Number: "SBIN0188983BN73",
  },
  {
    Action: "Approve",
    Name: "Cheyenne Levin",
    Email: "ebrown@aol.com",
    Phone_No: "+91 897 897 8812",
    Order_Date: "20 Aug 2024, 17:00",
    Expert_ID: "#120C24A1",
    Online_Status: "Active",
    City: "Lucknow",
    State: "Uttar Pradesh",
    Specialization: "Agreement management",
    Bar_Council_ID: "#WW947U",
    Prof_Type: "Lawyer",
    Degree: "B. Com",
    Language: "English",
    Bank_Name: "Punjab National Bank",
    Acc_Holder_Name: "Ram Kumar Sharma",
    Acc_No: "SBIN0188983BN73",
    IFSC_Code: "SBIN0188983BN73",
    PAN_Number: "SBIN0188983BN73",
  },
  {
    Action: "Waiting List",
    Name: "James Aminoff",
    Email: "slee@aol.com",
    Phone_No: "+91 897 897 8812",
    Order_Date: "20 Aug 2024, 17:00",
    Expert_ID: "#120C24A1",
    Online_Status: "Full",
    City: "Lucknow",
    State: "Uttar Pradesh",
    Specialization: "Agreement management",
    Bar_Council_ID: "#WW947U",
    Prof_Type: "CA",
    Degree: "B. Com",
    Language: "English",
    Bank_Name: "Punjab National Bank",
    Acc_Holder_Name: "Ram Kumar Sharma",
    Acc_No: "SBIN0188983BN73",
    IFSC_Code: "SBIN0188983BN73",
    PAN_Number: "SBIN0188983BN73",
  },
];
export default orderData;
